apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    database: ${DOCKER_INFLUXDB_INIT_BUCKET}
    jsonData:
      httpMode: POST
      version: InfluxQL
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'